<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-EventAgencyFinalProject-092e6abd-3e45-47c2-ad17-b6199ff88cb3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\css\create.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventAgency.Data\EventAgency.Data.csproj" />
    <ProjectReference Include="..\EventAgency.Services.Core\EventAgency.Services.Core.csproj" />
    <ProjectReference Include="..\EventAgency.Web.Infrastructure\EventAgency.Web.Infrastructure.csproj" />
    <ProjectReference Include="..\EventAgency.Web.ViewModels\EventAgency.Web.ViewModels.csproj" />
    <ProjectReference Include="..\EventAgencyFinalProject.GCommon\EventAgency.GCommon.csproj" />
  </ItemGroup>

</Project>
